CREATE TABLE CONFIGURATION(
CHATID INTEGER,
DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
USERNAME CHAR(48) DEFAULT '',
FIO CHAR(96) DEFAULT '',
LANGUAGE_CODE CHAR(8) DEFAULT '',
ACTION_ID INTEGER DEFAULT 0,
IS_ADMIN INTEGER DEFAULT 0
);

CREATE TABLE SESSIONS(
DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FIO CHAR(48) DEFAULT '',
ORDER_DATE CHAR(48) DEFAULT '',
PHONE CHAR(24) DEFAULT '',
ACTIVE INTEGER DEFAULT 0
);

CREATE TABLE SETTINGS(
MONITORING_STATUS INTEGER DEFAULT 0
);

--insert into configuration (chatid, username, fio, language_code, action_id) values ('234234',  'sdfsdfs', 'Kkdkfd Ljjmmf', 'ru', '0')

